version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./app:/app:cached
      # exclude volumes
      - /app/node_modules
    tty: true
    stdin_open: true
